### ISSUE TITLE
lsposed on alioth miui 12.5.

### ISSUE THREAD

**Issue by ExiledEye** [Xposed-Modules-Repo/name.mikanoshi.customiuizer#1]
Using lsposed on alioth on miui 12.5 and the app says that there is no xposed.
Someone other already had this issue but the app still worked even with the notification of no xposed, but for me the app simply doesn't work.
Also had a strange "problem": after uninstalling the app and at the moment i ve pressed install (play store and apk installation as well) the phone fast rebooted without finishing the installation.

**Comment by Mikanoshi** [comment]
Module should still work even with this message, it just doesn't know about LSPosed yet.

**Comment by ExiledEye** [comment]
> Module should still work even with this message, it just doesn't know about LSPosed yet.

I know, but not for me. 
I ve tried to apply something and reboot and nothing changed.

**Comment by ExiledEye** [comment]
After the update the app is recognizing LSPosed but it still doesn't work.
A this point i think miui 12.5 is the problem.
Poco F3 (Alioth) on miuimix stable (miui 12.5).

**Comment by Mikanoshi** [comment]
12.5 is not fully supported, even less so if it's Android 11.

**Comment by ExiledEye** [comment]
> 12.5 is not fully supported, even less so if it's Android 11.

Bonk.

**Comment by ExiledEye** [comment]
> 12.5 is not fully supported, even less so if it's Android 11.

Bonk.
