### ISSUE TITLE
Cant initialize SDK

### ISSUE THREAD

**Issue by RiccardoZappitelli** [Xposed-Modules-Repo/name.mikanoshi.customiuizer#2]
![IMG_20230308_115454](https://user-images.githubusercontent.com/63201347/223694830-4f174b04-9a68-4228-934d-ac5da6a281f4.jpg)

**Comment by RiccardoZappitelli** [comment]
I gave all the permissions and it is rooted

**Comment by Mikanoshi** [comment]
Module is for MIUI 10-12.5
